### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by iamale** [Amila-M/kl10tch#1]
![Screenshot](https://cloud.githubusercontent.com/assets/1298948/6360568/279523e6-bc8c-11e4-8acc-0cdfd0617336.png)
Firefox 30 on Linux Mint 16 / Openbox / Numix theme.

Алсо, хром:
![One more](https://cloud.githubusercontent.com/assets/1298948/6360608/7d876fa2-bc8c-11e4-97f9-495dc0bc3ce9.png)

Самое страшное -- не скроллит колёсиком в такой ситуации. :(

**Comment by skirushkin** [comment]
Да, проблема с падингом body и высотой нового футера. Исправим в следующем релизе. Спасибо за фитбек.

**Comment by iamale** [comment]
Подсказка: если убрать `overflow-x: hidden;` в `html, body {...}`, всё становится ок. Остаётся понять, почему так.

**Comment by skirushkin** [comment]
Да почему известно. Футер с абсолютным позиционированием (если контента мало то все равно внизу) при редизайне он увеличился, а падинг у боди для отступа от низа добавить забыли. Вот и получается второй скрол на body, так как его высота 100%  + выбивающийся футер. Оверфлоу - кастыль в данном случае, так как просто последствия скрывает. Лечить надо по-другому

**Comment by iamale** [comment]
> падинг у боди для отступа от низа добавить забыли

Попробовал `padding-bottom: 1000px`, не помогло. Хм~

**Comment by skirushkin** [comment]
на футер height: 85px;

**Comment by skirushkin** [comment]
Ну как? Закрываем?

**Comment by iamale** [comment]
@skirushkin Вроде похоже на правду. Ещё осталось #2 :/
